### ISSUE TITLE
antd-mobile 自定义 icon无效？

### ISSUE THREAD

**Issue by mayacger** [ant-design/antd-mobile-icons-v2#2]
使用<Icon type={require('path/to/svg')} />
安装"配置 webpack 以支持自定义 svg icon，具体可参见 Icon 文档"，配置后无效果。
具体还有其他什么地方要改？

**Comment by paranoidjk** [comment]
你给的没有任何有效信息， 我们无能为力。

仔细阅读文档https://mobile.ant.design/components/icon
或者参考官方demo https://github.com/ant-design/antd-mobile-samples
